lst_category_group_argentina=['Abrasives', 'Air Tools', 'Audio', 'Auto PT', 'Auto Specialty',
       'Bar Product', 'Batteries & Chargers', 'Bench & Stationary',
       'Blowers/Blower Vacs', 'Chalk & Reels', 'Clamps', 'Combo Kits',
       'Concrete Other', 'Demolition & Building', 'Diamonds', 'Drilling',
       'Drilling & Fastening', 'Drywall', 'Electrical Tools', 'Fastening',
       'Grinding', 'Hammers', 'Hand Vacumm', 'Hardlines',
       'Hedge Trimmers', 'Hex Keys', 'Kitchen Products',
       'Knives & Blades', 'Lasers', 'Levels', 'Linear Edge', 'Marking',
       'Mep', 'Mep Cutting', 'Metalworking', 'Mowers', 'Ope P&A',
       'Oscillating Tools', 'Other', 'Other - Cdiy', 'Other Measuring',
       'Painting', 'Pliers', 'Portable Woodworking', 'Pressure Washers',
       'Rotary Hammers', 'Saw Blades', 'Saws', 'Scraper Blades',
       'Screwdrivers', 'Snips', 'Squares', 'Stick Vacs', 'Storage',
       'String Trimmers', 'Tap & Die', 'Tapes', 'Tile & Masonry',
       'Tile Cutters', 'Vacuums & Dust Extra', 'Wood Cutting']

lst_category_group_bolivia=['Abrasives', 'Air Tools', 'Audio', 'Auto PT', 'Auto Specialty',
       'Batteries & Chargers', 'Bench & Stationary',
       'Blowers/Blower Vacs', 'Clamps', 'Combo Kits', 'Concrete Other',
       'Demolition & Building', 'Diamonds', 'Drilling',
       'Drilling & Fastening', 'Drywall', 'Fastening', 'Grinding',
       'Hammers', 'Hand Vacumm', 'Hardlines', 'Hedge Trimmers',
       'Hex Keys', 'Knives & Blades', 'Lasers', 'Levels', 'Lightning',
       'Linear Edge', 'Marking', 'Mep', 'Mep Cutting', 'Metalworking',
       'Mowers', 'Ope P&A', 'Oscillating Tools', 'Other', 'Other - Cdiy',
       'Other Measuring', 'Painting', 'Pliers', 'Portable Woodworking',
       'Pressure Washers', 'Rotary Hammers', 'Saw Blades', 'Saws',
       'Scraper Blades', 'Screwdrivers', 'Snips', 'Squares', 'Stick Vacs',
       'Storage', 'String Trimmers', 'Tap & Die', 'Tapes',
       'Tile & Masonry', 'Tile Cutters', 'Vacuums & Dust Extra',
       'Wood Cutting']

lst_category_group_brasil=['Abrasives', 'Air Tools', 'Auto PT', 'Auto Specialty', 'Band Saws',
       'Bar Product', 'Batteries & Chargers', 'Bench & Stationary',
       'Blowers/Blower Vacs', 'Chalk & Reels', 'Clamps',
       'Climate Control', 'Combo Kits', 'Concrete Other',
       'Demolition & Building', 'Diamonds', 'Drilling',
       'Drilling & Fastening', 'Drywall', 'Electrical Tools', 'Expansion',
       'Fastening', 'Garment & Personal Care', 'Grinding', 'Hammers',
       'Hand Vacumm', 'Hardlines', 'Hedge Trimmers', 'Hex Keys',
       'Home Products', 'Kitchen Products', 'Knives & Blades', 'Lasers',
       'Levels', 'Lightning', 'Linear Edge', 'Marking', 'Mep',
       'Mep Cutting', 'Metalworking', 'Mowers', 'Nailers', 'Ope P&A',
       'Oscillating Tools', 'Other', 'Other - Cdiy', 'Other Measuring',
       'Painting', 'Pliers', 'Por clasificar', 'Portable Woodworking',
       'Pressure Washers', 'Rotary Hammers', 'Saw Blades', 'Saws',
       'Scraper Blades', 'Screwdrivers', 'Snips', 'Specialty', 'Squares',
       'Steam', 'Stick Vacs', 'Storage', 'String Trimmers', 'Tap & Die',
       'Tapes', 'Tile & Masonry', 'Tile Cutters', 'Vacuums & Dust Extra',
       'Wood Cutting']

lst_category_group_chile=[ 'Abrasives', 'Air Tools', 'Auto PT', 'Auto Specialty',
       'Band Saws', 'Batteries & Chargers', 'Bench & Stationary',
       'Blowers/Blower Vacs', 'Chalk & Reels', 'Clamps', 'Combo Kits',
       'Concrete Other', 'Demolition & Building', 'Diamonds', 'Drilling',
       'Drilling & Fastening', 'Drywall', 'Electrical Tools', 'Fastening',
       'Grinding', 'Hammers', 'Hand Vacumm', 'Hardlines',
       'Hedge Trimmers', 'Hex Keys', 'Knives & Blades', 'Lasers',
       'Levels', 'Linear Edge', 'Marking', 'Mep', 'Mep Cutting',
       'Metalworking', 'Mowers', 'Nailers', 'Ope P&A',
       'Oscillating Tools', 'Other', 'Other - Cdiy', 'Other Measuring',
       'Painting', 'Pliers', 'Portable Woodworking', 'Pressure Washers',
       'Rotary Hammers', 'Saw Blades', 'Saws', 'Scraper Blades',
       'Screwdrivers', 'Snips', 'Squares', 'Stick Vacs', 'Storage',
       'String Trimmers', 'Tap & Die', 'Tapes', 'Tile Cutters',
       'Vacuums & Dust Extra', 'Wood Cutting']

lst_category_group_colombia=['Abrasives', 'Air Tools', 'Audio', 'Auto PT', 'Auto Specialty',
       'Band Saws', 'Batteries & Chargers', 'Bench & Stationary',
       'Blowers/Blower Vacs', 'Chalk & Reels', 'Clamps', 'Combo Kits',
       'Concrete Other', 'Demolition & Building', 'Diamonds', 'Drilling',
       'Drilling & Fastening', 'Drywall', 'Electrical Tools', 'Fastening',
       'Gardening', 'Grinding', 'Hammers', 'Hand Vacumm', 'Hardlines',
       'Hedge Trimmers', 'Hex Keys', 'Knives & Blades', 'Lasers',
       'Levels', 'Linear Edge', 'Marking', 'Mep', 'Mep Cutting',
       'Metalworking', 'OTHER', 'OTHER - CDIY', 'Ope P&A', 'Other',
       'Other - Cdiy', 'Other Measuring', 'Pliers', 'Por clasificar',
       'Portable Woodworking', 'Pressure Washers', 'Rotary Hammers',
       'Saw Blades', 'Saws', 'Scraper Blades', 'Screwdrivers', 'Snips',
       'Squares', 'Stick Vacs', 'Storage', 'String Trimmers', 'Tap & Die',
       'Tapes', 'Tile & Masonry', 'Tile Cutters', 'Vacuums & Dust Extra',
       'Wood Cutting']

lst_category_group_ecuador=['Abrasives', 'Air Tools', 'Audio', 'Auto PT', 'Auto Specialty',
       'Band Saws', 'Batteries & Chargers', 'Bench & Stationary',
       'Blowers/Blower Vacs', 'Chalk & Reels', 'Clamps', 'Combo Kits',
       'Concrete Other', 'Demolition & Building', 'Diamonds', 'Drilling',
       'Drilling & Fastening', 'Drywall', 'Electrical Tools', 'Fastening',
       'Gardening', 'Grinding', 'Hammers', 'Hand Vacumm', 'Hardlines',
       'Hedge Trimmers', 'Hex Keys', 'Knives & Blades', 'Lasers',
       'Levels', 'Lightning', 'Linear Edge', 'Marking', 'Mep',
       'Mep Cutting', 'Metalworking', 'Mowers', 'Ope P&A', 'Other',
       'Other - Cdiy', 'Other Measuring', 'Painting', 'Pliers',
       'Portable Woodworking', 'Pressure Washers', 'Rotary Hammers',
       'Saw Blades', 'Saws', 'Scraper Blades', 'Screwdrivers', 'Snips',
       'Specialty', 'Squares', 'Stick Vacs', 'Storage', 'String Trimmers',
       'Tap & Die', 'Tapes', 'Tile & Masonry', 'Tile Cutters',
       'Vacuums & Dust Extra', 'Wood Cutting']

lst_category_group_mexico=['Abrasives', 'Air Tools', 'Audio', 'Auto PT', 'Auto Specialty',
       'Band Saws', 'Batteries & Chargers', 'Bench & Stationary',
       'Blowers/Blower Vacs', 'Chalk & Reels', 'Clamps', 'Combo Kits',
       'Concrete Other', 'Demolition & Building', 'Diamonds', 'Drilling',
       'Drilling & Fastening', 'Drywall', 'Electrical Tools', 'Fastening',
       'Gardening', 'Grinding', 'Hammers', 'Hand Vacumm', 'Hardlines',
       'Hedge Trimmers', 'Hex Keys', 'Knives & Blades', 'Lasers',
       'Levels', 'Lightning', 'Linear Edge', 'Marking', 'Mep',
       'Mep Cutting', 'Metalworking', 'Mowers', 'Nailers', 'Ope P&A',
       'Other', 'Other - Cdiy', 'Other Measuring', 'Painting', 'Pliers',
       'Por clasificar', 'Portable Woodworking', 'Pressure Washers',
       'Rotary Hammers', 'Saw Blades', 'Saws', 'Scraper Blades',
       'Screwdrivers', 'Snips', 'Squares', 'Stick Vacs', 'Storage',
       'String Trimmers', 'Tap & Die', 'Tapes', 'Tile & Masonry',
       'Tile Cutters', 'Vacuums & Dust Extra', 'Wood Cutting']

lst_category_group_peru=['Abrasives', 'Air Tools', 'Audio', 'Auto PT', 'Auto Specialty',
       'Batteries & Chargers', 'Bench & Stationary',
       'Blowers/Blower Vacs', 'Chalk & Reels', 'Clamps', 'Combo Kits',
       'Concrete Other', 'Demolition & Building', 'Diamonds', 'Drilling',
       'Drilling & Fastening', 'Drywall', 'Electrical Tools', 'Fastening',
       'Grinding', 'Hammers', 'Hand Vacumm', 'Hardlines',
       'Hedge Trimmers', 'Hex Keys', 'Knives & Blades', 'Lasers',
       'Levels', 'Lightning', 'Linear Edge', 'Marking', 'Mep',
       'Mep Cutting', 'Metalworking', 'Mowers', 'Ope P&A', 'Other',
       'Other - Cdiy', 'Other Measuring', 'Painting', 'Pliers',
       'Por clasificar', 'Portable Woodworking', 'Pressure Washers',
       'Rotary Hammers', 'Saw Blades', 'Saws', 'Scraper Blades',
       'Screwdrivers', 'Snips', 'Squares', 'Storage', 'String Trimmers',
       'Tap & Die', 'Tapes', 'Tile Cutters', 'Vacuums & Dust Extra',
       'Wood Cutting']


filtros=[
    {'country':'Argentina',
     'category group':lst_category_group_argentina},

    {'country':'Bolivia',
     'category group':lst_category_group_bolivia},

    {'country':'Brasil',
     'category group':lst_category_group_brasil},

    {'country':'Chile',
     'category group':lst_category_group_chile},

    {'country':'Colombia',
     'category group':lst_category_group_colombia},

    {'country':'Ecuador',
     'category group':lst_category_group_ecuador},
    
    {'country':'Mexico',
     'category group':lst_category_group_mexico},
    
    {'country':'Peru',
     'category group':lst_category_group_peru}
]

filtros_country=['Argentina',
'Bolivia',
'Brasil',
'Chile',
'Colombia',
'Ecuador',
'Mexico',
'Peru']